name: 'Set up WordPress Test Library'
description: 'Sets up WordPress and WordPress test library'
author: 'Volodymyr Kolesnykov'
inputs:
  version:
    description: 'WordPress version'
    required: false
    default: 'latest'
  cache_prefix:
    description: 'Custom cache prefix'
    required: false
    default: ''
  dir:
    description: 'Directory to install WordPress and WordPress Test Library'
    required: false
    default: '/tmp'
  db_user:
    description: 'Database user'
    required: false
    default: 'wordpress'
  db_password:
    description: 'Database password'
    required: false
    default: 'wordpress'
  db_name:
    description: 'Database name'
    required: false
    default: 'wordpress_test'
  db_host:
    description: 'Database host'
    required: false
    default: '127.0.0.1'

outputs:
  wp_version:
    description: 'Actual WordPress version'

runs:
  using: 'node20'
  main: 'dist/setup/index.js'
  post: 'dist/post/index.js'

branding:
  color: blue
  icon: target
